### ISSUE TITLE
Compressed/Purgeable Memory Question

### ISSUE THREAD

**Issue by macbellingrath** [nicklockwood/LRUCache#2]
This is more of a question / curiosity than a request to fix something.

From past WWDCs, I remember that the advice for building memory efficient caching implementations, it is better to allow the memory to be compressed and to **not** evict objects during memory warnings. 
https://github.com/nicklockwood/LRUCache/blob/2d487e109f6d577a517682a984a1e369336eeafb/Sources/LRUCache.swift#L84

```swift
  self.token = notificationCenter.addObserver(
            forName: UIApplication.didReceiveMemoryWarningNotification,
            object: nil,
            queue: nil
        ) { [weak self] _ in
            self?.removeAllValues()
        }
```

WWDC - https://developer.apple.com/videos/play/wwdc2018/416/?time=385

I'm curious how one would go about supporting that? As I understand, NSCache supports this by allocating memory in a special way. 

```
One other note is that if you use an NSCache instead of a dictionary, that's a threat-safe way to store cached objects. And because of the way NSCache allocates its memory, it's actually purgeable, so it works even better in a memory-constrained environment. 
```

How would one go about supporting this behavior in LRUCache? Thanks 😊

**Comment by nicklockwood** [comment]
Thanks for the link! I hadn't seen that video before, and it's quite interesting. Unfortunately I wasn't able to get much idea of what exactly NSCache is doing under the hood from the description. I thought I might be able to gain some insight by looking at the source code for the Swift Foundation implementation, but either I'm missing something obvious, or it doesn't share the magic purging and compressing features of its Objective-C counterpart.

https://github.com/apple/swift-corelibs-foundation/blob/a5f74c3d7f664f705b86862a51919e44bf1bd97e/Foundation/NSCache.swift

From what I can see, it's ordering objects by cost internally though (as opposed to recently-used), which is interesting.

Regarding:

> From past WWDCs, I remember that the advice for building memory efficient caching implementations, it is better to allow the memory to be compressed and to not evict objects during memory warnings.

It might be better to make that functionality optional, or to only clear some objects, or even to disable it altogether. I'm not sure how to benchmark that though.

Regarding:

> One other note is that if you use an NSCache instead of a dictionary, that's a threat-safe way to store cached objects. And because of the way NSCache allocates its memory, it's actually purgeable, so it works even better in a memory-constrained environment. 

LRUCache is already thread-safe, but I assume that the purgeable behavior relates to [NSPurgeableData](https://developer.apple.com/documentation/foundation/nspurgeabledata), which according to the docs can be used on its own without needing NSCache anyway, so perhaps merely storing cache data in `NSPurgeableData` containers would be sufficient? (which you could do in conjunction with LRUCache, though perhaps there's some way I could expose a nicer API for it)

**Comment by macbellingrath** [comment]
Thank you for the reply. A rough strategy might be to:
- implement either NSPurgeableData container or a wrapper type that implements [NSDiscardableContent](https://developer.apple.com/documentation/foundation/nsdiscardablecontent)
- when evicting objects from the cache under normal conditions, remove from internal storage and then decrement the counter and "discard" the container
- when evicting objects under memory pressure, decrement the access counter on the container and attempt to discard the container but do not necessarily remove from internal storage 
- when returning objects from the cache, check the counter/isDiscarded before returning the object and clean up in that case?
